### ISSUE TITLE
Cannot curl through SOCKS server

### ISSUE THREAD

**Issue by jimmy-ly00** [calebmadrigal/socks5-server-py#1]
I'm trying to curl a website through the SOCKS proxy, but not getting a response. This should work, as I have done so with other socks server. I am running python 2.7 on Linux kali 4.6.0-kali1-amd64 

```
root@kali:~# python socks5.py
2017-06-16 19:19:57,923: socks5_server (INFO): Serving on :1080
2017-06-16 19:19:59,836: socks5_server (INFO): Connection from: 127.0.0.1:50312
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "socks5.py", line 162, in handle_connect_thread
    dest_host, dest_port = self.establish_socks5(client_sock)
  File "socks5.py", line 131, in establish_socks5
    dst_port = chr_to_int(dst_port[0]) * 256 + chr_to_int(dst_port[1])
TypeError: 'NoneType' object has no attribute '__getitem__'
```
Then I curl:
```
root@kali:~# curl --socks5 localhost:1080 google.com
curl: (7) Failed to receive SOCKS5 connect request ack.
```

**Comment by madbird1304** [comment]
Better later than never: #4
